name: CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: "ubuntu-18.04"
    env:
      OPENRESTY_PREFIX: "/usr/local/openresty"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Linux Get dependencies
        run: sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl luarocks

      - name: Linux Before install
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          sudo luarocks install luacheck

      - name: Linux Install
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty

      - name: Install Dependency
        run: |
          curl https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh -sL | sh -
          sudo make deps

      - name: Linux Script
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          make test
